name: goreleaser

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  goreleaser:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Fetch all tags
        run: git fetch --force --tags
      - name: Set up Go
        uses: actions/setup-go@v5.1.0
        with:
          go-version: 1.23.3
      - name: Install Go packages
        run: |
          go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest
          go install github.com/dmarkham/enumer@latest
      - name: Setup Node
        uses: actions/setup-node@v4.1.0
      - name: Install dependencies
        working-directory: web/ui
        run: npm install
      - name: Generate web UI assets
        working-directory: web/ui
        run: npm run build
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5.1.0
        with:
          distribution: goreleaser
          version: "2.4.6"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SCOOP_TAP_GITHUB_TOKEN: ${{ secrets.SCOOP_TAP_GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
