name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    env:
      GOFLAGS: -mod=readonly

    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.3
      - name: Setup Node
        uses: actions/setup-node@v4.1.0
      - name: Install dependencies
        working-directory: web/ui
        run: npm install
      - name: Generate web UI assets
        working-directory: web/ui
        run: npm run build
      - name: Test
        run: go test -race -v ./...
        if: runner.os != 'Windows'

      - name: Test (without race detector)
        run: go test -v ./...
        if: runner.os == 'Windows'
