openapi: "3.0.0"
info:
  version: 1.0.0
  title: Mangal WEB UI
paths:
  /image:
    get:
      description: Get image from URL bypassing CORS policy
      operationId: getImage
      parameters:
        - name: url
          in: query
          description: image url to download
          required: true
          schema:
            type: string
        - name: referer
          in: query
          description: referer to use to get the image
          required: false
          schema:
            type: string
      responses:
        '200':
          description: image response
          content:
            image/png:
              schema:
                $ref: '#/components/schemas/Image'
  /mangalInfo:
    get:
      description: Get information about installed Mangal app
      operationId: getMangalInfo
      responses:
        '200':
          description: mangal info response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MangalInfo'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /providers:
    get:
      description: |
        Get avaiable providers
      operationId: getProviders
      responses:
        '200':
          description: providers response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Provider'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /searchMangas:
    get:
      description: Search for mangas
      operationId: searchMangas
      parameters:
        - name: provider
          in: query
          description: provider id to use
          required: true
          schema:
            type: string
        - name: query
          in: query
          description: manga search query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: search results
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Manga'

        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Image:
      type: string
      format: binary

    Provider:
      type: object
      required:
        - id
        - version
        - name
      properties:
        name:
          type: string
        id:
          type: string    
        description:
          type: string
        version:
          type: string

    Manga:
      type: object
      required:
        - title
        - id
      properties:
        id:
          type: string
        title:
          type: string
        url:
          type: string
        banner:
          type: string
        cover:
          type: string

    MangalInfo:
      type: object
      required:
        - version
      properties:
        version:
          type: string

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
